# -*- coding: utf-8 -*-
"""armstrong numbers.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G2EEu46Q2BhOlrh0eNIQmy2MNL2xpJ65
"""

armst = input('Enter a number: ')
armst2 = 0
if type(armst) != "str"  and armst.isdecimal() and not isinstance(armst, float) and float(armst) > 0:
  for i in str(armst):
    armst2 += int(i) ** int(len(armst))
  if int(armst) == armst2:
    print(f'{armst} is an armstrong number!')
  else:
    print(f'{armst} is NOT an armstrong number!')
else:
  print("It is an invalid entry. Don't use non-numeric, float, or negative values!")