# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qtm3qnupVCLwC6FXCHeGkII8hUQ9aODI
"""

fib = []
i = 1
counter = 0
while i <56:
  if fib != []:
    fib.append(i)
    i = i + fib[counter-1]
    counter += 1 
  else:
    fib.append(i)
    counter += 1
print(fib)

