# -*- coding: utf-8 -*-
"""letters_count.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F2LcA1PRR5XiBnDdVzD2bJ2LDaDcWrE0
"""

word = input('Please enter a sentence: ')
word_dict = {}
for i in word:
  if i not in word_dict.keys():
    word_dict[i] = 1
  else:
    word_dict[i] += 1
print(word_dict)

