# -*- coding: utf-8 -*-
"""prime_numbers.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tuqyhDQJAz6Vj1P8zSSIgEPG9HWrq5DM
"""

num = input('Enter a number please:  ')
num = int(num)
dividers = []
if num > 1:
  for i in range(2,num):
    if num % i != 0:
      continue
    else:
      dividers.append(i)
  if dividers == []:
    print(f'{num} is a prime number.')
  else:
    print(f'{num} is not a prime number.')
else:
  print(f'{num} is not a prime number.')