# -*- coding: utf-8 -*-
"""prime_nums_list

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19GXanpB5aARaFYDhtTZkWG67hA5CneNF
"""

num = int(input('Enter a number please:  '))

if num > 2:
  prime_list = []
  for j in range(2, num + 1):
    dividers = []
    for i in range(2,j):
      if j % i != 0:
        continue
      else:
        dividers.append(i)
    if dividers == []:
      prime_list.append(j)
    else:
      continue
  print(prime_list)
else:
  print(f'{num} is not a valid number.')

